SET PATH=D:\Program Files\Keil\ARM\BIN40;C:\Program Files\NVIDIA Corporation\PhysX\Common;e:\Program Files\CollabNet;e:\Program Files\Embarcadero\RAD Studio\11.0\bin;C:\Users\Public\Documents\RAD Studio\11.0\Bpl;e:\Program Files\Embarcadero\RAD Studio\11.0\bin64;C:\Users\Public\Documents\RAD Studio\11.0\Bpl\Win64;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
SET CPU_TYPE=STM32F103ZE
SET CPU_VENDOR=STMicroelectronics
SET UV2_TARGET=MyMP3
SET CPU_CLOCK=0x007A1200
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via "..\obj\main.__i"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via "..\obj\stm32f10x_it.__i"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via "..\obj\delay.__i"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via "..\obj\sdio.__i"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via "..\obj\usart.__i"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via "..\obj\iap.__i"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via "..\obj\stmflash.__i"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via "..\obj\diskio.__i"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via "..\obj\ff.__i"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via "..\obj\misc.__i"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via "..\obj\stm32f10x_dma.__i"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via "..\obj\stm32f10x_exti.__i"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via "..\obj\stm32f10x_fsmc.__i"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via "..\obj\stm32f10x_gpio.__i"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via "..\obj\stm32f10x_rcc.__i"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via "..\obj\stm32f10x_sdio.__i"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via "..\obj\stm32f10x_spi.__i"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via "..\obj\stm32f10x_tim.__i"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via "..\obj\stm32f10x_usart.__i"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via "..\obj\stm32f10x_flash.__i"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via "..\obj\core_cm3.__i"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmAsm" --Via "..\obj\startup_stm32f10x_hd._ia"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via "..\obj\system_stm32f10x.__i"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
"D:\Program Files\Keil\ARM\BIN40\ArmLink" --Via "..\Obj\Boot.lnp"
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
D:\Program Files\Keil\ARM\BIN40\fromelf.exe "..\Obj\Boot.axf" --i32combined --output "..\Obj\Boot.hex"
fromelf.exe --bin -o "..\Obj\Boot.bin" "..\Obj\Boot.axf"
